export const userData = {
  name: "김민준",
  title: "풀스택 개발자 지망생",
  level: 12,
  xp: 2450,
  xpToNextLevel: 3000,
  stage: "성장기",
  stageIndex: 1,
  totalMissionsCompleted: 47,
  streak: 14,
  joinDate: "2024-01-15",
  badges: ["🔥 연속 달성", "⚡ 빠른 학습자", "🎯 목표 달성"],
};

export const competencyData = [
  { subject: "AI/ML", value: 75, fullMark: 100 },
  { subject: "개발", value: 82, fullMark: 100 },
  { subject: "클라우드", value: 60, fullMark: 100 },
  { subject: "보안", value: 45, fullMark: 100 },
  { subject: "DevOps", value: 55, fullMark: 100 },
  { subject: "데이터", value: 68, fullMark: 100 },
];

export const levelProgressData = [
  { month: "11월", level: 8 },
  { month: "12월", level: 9 },
  { month: "1월", level: 10 },
  { month: "2월", level: 11 },
  { month: "3월", level: 12 },
  { month: "4월", level: 12 },
];

export const xpHistoryData = [
  { day: "월", xp: 120 },
  { day: "화", xp: 280 },
  { day: "수", xp: 180 },
  { day: "목", xp: 350 },
  { day: "금", xp: 220 },
  { day: "토", xp: 400 },
  { day: "일", xp: 160 },
];

// 일자별 미션 수행 수 데이터
export const dailyMissionCountData = [
  { day: "월", count: 2 },
  { day: "화", count: 5 },
  { day: "수", count: 3 },
  { day: "목", count: 6 },
  { day: "금", count: 4 },
  { day: "토", count: 7 },
  { day: "일", count: 3 },
];

export const dailyMissions = [
  {
    id: "d1",
    title: "ChatGPT 프롬프트 엔지니어링 실습",
    description: "고급 프롬프트 기법 3가지를 실습하고 결과를 기록하세요.",
    category: "AI/ML",
    xp: 50,
    completed: true,
    difficulty: "보통",
  },
  {
    id: "d2",
    title: "React 컴포넌트 최적화",
    description: "useMemo와 useCallback을 활용한 성능 최적화 1개 구현",
    category: "개발",
    xp: 40,
    completed: true,
    difficulty: "어려움",
  },
  {
    id: "d3",
    title: "IT 뉴스 3개 스크랩 & 요약",
    description: "오늘의 주요 AI/IT 뉴스를 읽고 핵심 인사이트 정리",
    category: "일반",
    xp: 20,
    completed: false,
    difficulty: "쉬움",
  },
  {
    id: "d4",
    title: "알고리즘 문제 풀기 (1문제)",
    description: "LeetCode Medium 난이도 문제 1개 풀기",
    category: "개발",
    xp: 60,
    completed: false,
    difficulty: "어려움",
  },
  {
    id: "d5",
    title: "Docker 컨테이너 실습",
    description: "간단한 웹앱을 Docker로 컨테이너화 실습",
    category: "DevOps",
    xp: 45,
    completed: false,
    difficulty: "보통",
  },
];

export const weeklyMissions = [
  {
    id: "w1",
    title: "개인 프로젝트 README 작성",
    description: "GitHub 프로젝트에 상세한 README.md 문서 작성",
    category: "개발",
    xp: 150,
    completed: true,
    difficulty: "보통",
    dueDate: "4월 19일",
  },
  {
    id: "w2",
    title: "AWS 기초 자격증 모의고사",
    description: "AWS Cloud Practitioner 모의고사 1회 완료",
    category: "클라우드",
    xp: 200,
    completed: false,
    difficulty: "어려움",
    dueDate: "4월 20일",
  },
  {
    id: "w3",
    title: "오픈소스 기여 1건",
    description: "관심 있는 오픈소스 프로젝트에 PR 1개 제출",
    category: "개발",
    xp: 300,
    completed: false,
    difficulty: "매우 어려움",
    dueDate: "4월 21일",
  },
  {
    id: "w4",
    title: "AI 논문 스터디",
    description: "최신 AI 논문 1편 읽고 주요 내용 정리",
    category: "AI/ML",
    xp: 180,
    completed: true,
    difficulty: "어려움",
    dueDate: "4월 22일",
  },
  {
    id: "w5",
    title: "네트워크 기초 학습",
    description: "TCP/IP, HTTP/HTTPS 개념 정리 및 정리 노트 작성",
    category: "보안",
    xp: 120,
    completed: false,
    difficulty: "보통",
    dueDate: "4월 23일",
  },
];

export const monthlyMissions = [
  {
    id: "m1",
    title: "풀스택 토이 프로젝트 완성",
    description: "React + Node.js로 간단한 CRUD 앱 완성 및 배포",
    category: "개발",
    xp: 800,
    completed: false,
    difficulty: "매우 어려움",
    progress: 65,
    dueDate: "4월 30일",
  },
  {
    id: "m2",
    title: "AI 활용 포트폴리오 작성",
    description: "AI 도구를 활용한 작업 사례 3개 이상 포트폴리오에 추가",
    category: "AI/ML",
    xp: 500,
    completed: false,
    difficulty: "어려움",
    progress: 40,
    dueDate: "4월 30일",
  },
  {
    id: "m3",
    title: "기술 블로그 포스팅 4편",
    description: "배운 내용을 블로그에 정리하여 4편 이상 발행",
    category: "일반",
    xp: 400,
    completed: true,
    difficulty: "보통",
    progress: 100,
    dueDate: "4월 30일",
  },
  {
    id: "m4",
    title: "코딩 테스트 대비 50문제",
    description: "알고리즘 문제 50개 풀어 코딩 테스트 준비",
    category: "개발",
    xp: 600,
    completed: false,
    difficulty: "어려움",
    progress: 72,
    dueDate: "4월 30일",
  },
];

export const newsItems = [
  {
    id: "n1",
    title: "GPT-5 출시 임박: OpenAI, 다음 달 공개 예정",
    summary:
      "OpenAI가 GPT-5를 다음 달 공개할 예정이며, 추론 능력과 멀티모달 기능이 크게 향상된 것으로 알려졌습니다. 코딩, 수학, 과학 분야에서 혁신적인 성능을 보여줄 것으로 기대됩니다.",
    category: "AI",
    source: "TechCrunch",
    date: "2026-04-17",
    readTime: "3분",
    url: "#",
    imageUrl: "https://images.unsplash.com/photo-1775185172785-4bbd6b0fc8f5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    hot: true,
  },
  {
    id: "n2",
    title: "Vercel, Next.js 15.3 릴리즈: Turbopack 정식 지원",
    summary:
      "Vercel이 Next.js 15.3을 출시하며 Turbopack을 정식 지원합니다. 빌드 속도가 기존 대비 최대 10배 향상되었으며, React 19 서버 컴포넌트와의 통합이 더욱 강화되었습니다.",
    category: "개발",
    source: "Vercel Blog",
    date: "2026-04-16",
    readTime: "4분",
    url: "#",
    imageUrl: "https://images.unsplash.com/photo-1672385277648-85eddc237a2b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    hot: false,
  },
  {
    id: "n3",
    title: "AWS re:Invent 2026 주요 발표 정리",
    summary:
      "AWS re:Invent에서 새로운 AI 인프라 서비스들이 대거 공개되었습니다. Bedrock 업데이트, 새로운 EC2 인스턴스 타입, 그리고 서버리스 AI 파이프라인 도구가 주목받았습니다.",
    category: "서비스",
    source: "AWS Blog",
    date: "2026-04-15",
    readTime: "6분",
    url: "#",
    imageUrl: "https://images.unsplash.com/photo-1744868562210-fffb7fa882d9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    hot: false,
  },
  {
    id: "n4",
    title: "GitHub Copilot, 에이전트 모드 전면 도입",
    summary:
      "GitHub Copilot이 자율적으로 코드를 작성하고 테스트까지 수행하는 에이전트 모드를 전면 도입했습니다. 개발자의 지시에 따라 복잡한 작업을 자동으로 처리할 수 있게 됩니다.",
    category: "도구",
    source: "GitHub Blog",
    date: "2026-04-14",
    readTime: "5분",
    url: "#",
    imageUrl: "https://images.unsplash.com/photo-1672385277648-85eddc237a2b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    hot: true,
  },
  {
    id: "n5",
    title: "국내 AI 스타트업 투자 유치 급증: 2026년 1분기 분석",
    summary:
      "2026년 1분기 국내 AI 스타트업 투자가 전년 동기 대비 280% 증가했습니다. 특히 B2B SaaS와 AI 에이전트 분야에 투자가 집중되었으며, 시리즈 A 평균 투자액도 크게 늘었습니다.",
    category: "서비스",
    source: "한국경제",
    date: "2026-04-13",
    readTime: "4분",
    url: "#",
    imageUrl: "https://images.unsplash.com/photo-1775185172785-4bbd6b0fc8f5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    hot: false,
  },
  {
    id: "n6",
    title: "Cursor AI 2.0: 멀티 에이전트 코딩 환경 출시",
    summary:
      "인기 AI 코딩 에디터 Cursor가 2.0 버전을 출시했습니다. 여러 AI 에이전트가 동시에 협업하여 코드를 작성하는 멀티 에이전트 기능이 핵심으로, 복잡한 프로젝트 개발 속도를 혁신적으로 향상시킵니다.",
    category: "도구",
    source: "Product Hunt",
    date: "2026-04-12",
    readTime: "3분",
    url: "#",
    imageUrl: "https://images.unsplash.com/photo-1768839720936-87ce3adf2d08?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    hot: true,
  },
  {
    id: "n7",
    title: "Python 3.14 베타 출시: 타입 시스템 대폭 강화",
    summary:
      "Python 3.14 베타가 공개되었습니다. 정적 타입 분석 기능이 강화되고, JIT 컴파일러 성능이 개선되어 실행 속도가 최대 30% 빨라졌습니다. 개발자 커뮤니티의 기대가 큽니다.",
    category: "개발",
    source: "Python.org",
    date: "2026-04-11",
    readTime: "5분",
    url: "#",
    imageUrl: "https://images.unsplash.com/photo-1672385277648-85eddc237a2b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    hot: false,
  },
  {
    id: "n8",
    title: "LLM 보안 취약점 발견: 프롬프트 인젝션 대응 가이드",
    summary:
      "보안 연구팀이 주요 LLM 서비스에서 새로운 프롬프트 인젝션 취약점을 발견했습니다. 기업 환경에서의 AI 도구 사용 시 주의가 필요하며, 각 서비스사의 대응 방안도 공유됩니다.",
    category: "AI",
    source: "SecurityWeek",
    date: "2026-04-10",
    readTime: "7분",
    url: "#",
    imageUrl: "https://images.unsplash.com/photo-1768839720936-87ce3adf2d08?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&w=400",
    hot: false,
  },
];

export const quizData = [
  {
    id: "q1",
    category: "AI/ML",
    question: "트랜스포머(Transformer) 아키텍처에서 'Attention Is All You Need' 논문의 핵심 메커니즘은?",
    options: [
      "Recurrent Neural Network",
      "Self-Attention Mechanism",
      "Convolutional Neural Network",
      "Long Short-Term Memory",
    ],
    correct: 1,
    explanation:
      "Self-Attention은 입력 시퀀스의 각 위치가 다른 모든 위치와 직접 관계를 맺을 수 있게 하여 장거리 의존성 문제를 해결합니다.",
    xp: 30,
  },
  {
    id: "q2",
    category: "개발",
    question: "React에서 불필요한 리렌더링을 방지하기 위해 함수를 메모이제이션할 때 사용하는 훅은?",
    options: ["useState", "useEffect", "useCallback", "useReducer"],
    correct: 2,
    explanation:
      "useCallback은 함수를 메모이제이션하여 의존성이 변경되지 않으면 동일한 함수 참조를 반환합니다.",
    xp: 25,
  },
  {
    id: "q3",
    category: "클라우드",
    question: "AWS에서 서버리스 함수 실행을 위한 핵심 서비스는?",
    options: ["EC2", "ECS", "Lambda", "Fargate"],
    correct: 2,
    explanation:
      "AWS Lambda는 서버 관리 없이 코드를 실행할 수 있는 서버리스 컴퓨팅 서비스입니다.",
    xp: 20,
  },
  {
    id: "q4",
    category: "보안",
    question: "SQL Injection을 방지하는 가장 효과적인 방법은?",
    options: [
      "입력값 길이 제한",
      "Prepared Statements 사용",
      "HTTPS 적용",
      "방화벽 설치",
    ],
    correct: 1,
    explanation:
      "Prepared Statements(매개변수화 쿼리)는 사용자 입력을 쿼리 구조와 분리하여 SQL Injection을 근본적으로 방지합니다.",
    xp: 35,
  },
  {
    id: "q5",
    category: "DevOps",
    question: "CI/CD 파이프라인에서 'CD'가 의미하는 것은?",
    options: [
      "Code Deployment",
      "Continuous Delivery/Deployment",
      "Container Docker",
      "Cloud Development",
    ],
    correct: 1,
    explanation:
      "CD는 Continuous Delivery(지속적 전달) 또는 Continuous Deployment(지속적 배포)를 의미하며, 코드 변경 사항을 자동으로 프로덕션에 배포하는 과정입니다.",
    xp: 20,
  },
];

export const portfolioItems = [
  {
    id: "p1",
    title: "AI 챗봇 프로토타입 개발",
    description: "OpenAI API를 활용한 고객 상담 챗봇 프로토타입 개발. React + FastAPI 구성",
    category: "AI/ML",
    completedDate: "2026-03-20",
    xpEarned: 800,
    tags: ["React", "Python", "OpenAI API", "FastAPI"],
    source: "월간 미션",
    githubUrl: "#",
  },
  {
    id: "p2",
    title: "기술 블로그 4편 작성",
    description: "React 최적화, Docker 입문, AI 프롬프트 엔지니어링, 클라우드 아키텍처 주제로 글 작성",
    category: "일반",
    completedDate: "2026-03-15",
    xpEarned: 400,
    tags: ["기술 글쓰기", "블로그"],
    source: "월간 미션",
    githubUrl: "#",
  },
  {
    id: "p3",
    title: "AWS 실습 환경 구성",
    description: "EC2, S3, RDS를 활용한 3-tier 웹 아키텍처 구성 실습 완료",
    category: "클라우드",
    completedDate: "2026-02-28",
    xpEarned: 350,
    tags: ["AWS", "EC2", "S3", "RDS"],
    source: "주간 미션",
    githubUrl: "#",
  },
  {
    id: "p4",
    title: "오픈소스 기여 - eslint-plugin",
    description: "react-hooks eslint 플러그인 버그 수정 PR 머지 완료",
    category: "개발",
    completedDate: "2026-02-10",
    xpEarned: 300,
    tags: ["오픈소스", "ESLint", "JavaScript"],
    source: "주간 미션",
    githubUrl: "#",
  },
  {
    id: "p5",
    title: "Docker + Kubernetes 입문 실습",
    description: "컨테이너 오케스트레이션 기초 학습 및 간단한 클러스터 구성",
    category: "DevOps",
    completedDate: "2026-01-25",
    xpEarned: 450,
    tags: ["Docker", "Kubernetes", "DevOps"],
    source: "월간 미션",
    githubUrl: "#",
  },
  {
    id: "p6",
    title: "SQL 보안 취약점 스터디",
    description: "OWASP Top 10 기반 주요 보안 취약점 학습 및 방어 기법 정리",
    category: "보안",
    completedDate: "2026-01-10",
    xpEarned: 280,
    tags: ["보안", "OWASP", "SQL"],
    source: "주간 미션",
    githubUrl: "#",
  },
];

export const calendarMissions: Record<string, { title: string; type: "daily" | "weekly" | "monthly"; completed: boolean }[]> = {
  "2026-04-01": [{ title: "React 훅 학습", type: "daily", completed: true }],
  "2026-04-02": [{ title: "알고리즘 2문제", type: "daily", completed: true }],
  "2026-04-03": [{ title: "Docker 실습", type: "daily", completed: true }],
  "2026-04-05": [
    { title: "IT 뉴스 스크랩", type: "daily", completed: true },
    { title: "AWS 모의고사", type: "weekly", completed: false },
  ],
  "2026-04-07": [{ title: "주간 미션 점검", type: "weekly", completed: true }],
  "2026-04-08": [{ title: "오픈소스 PR", type: "weekly", completed: false }],
  "2026-04-10": [{ title: "AI 프롬프트 실습", type: "daily", completed: true }],
  "2026-04-12": [
    { title: "코딩 테스트 5문제", type: "daily", completed: true },
    { title: "블로그 포스팅", type: "monthly", completed: true },
  ],
  "2026-04-14": [{ title: "네트워크 학습", type: "weekly", completed: false }],
  "2026-04-15": [{ title: "ChatGPT 프롬프트", type: "daily", completed: true }],
  "2026-04-17": [
    { title: "React 최적화", type: "daily", completed: true },
    { title: "뉴스 스크랩", type: "daily", completed: false },
  ],
  "2026-04-20": [{ title: "AWS 자격증 준비", type: "weekly", completed: false }],
  "2026-04-24": [{ title: "월간 프로젝트 마일스톤", type: "monthly", completed: false }],
  "2026-04-30": [
    { title: "포트폴리오 업데이트", type: "monthly", completed: false },
    { title: "코딩 테스트 50문제 달성", type: "monthly", completed: false },
  ],
};